app/fetcher/urls.py
from django.urls import path

from . import views

app_name = "fetcher"

urlpatterns = [
    path('', views.reference_fetcher_view, name='fetcher'),
    path('species_list/', views.ensembl_list_view, name='species_list'),
    path('version_list/', views.version_list_view, name='version_list'),
    path('missing/', views.missing_species_view, name='missing'),
]

app/reference_fetcher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from upload.views import image_upload
from fetcher.views import reference_fetcher_view

urlpatterns = [
    # path("", image_upload, name="upload"),
    # path("", reference_fetcher_view, name="fetcher"),
    path("", include('fetcher.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/fetcher/models.py
from django.db import models

# Create your models here.


class Fetch(models.Model):
    id = models.BigAutoField(primary_key=True)
    fetch_id = models.CharField(max_length=50)
    species = models.CharField(max_length=80)
    ensembl_version = models.CharField(max_length=50)
    reference = models.CharField(max_length=50)

    def __str__(self):
        return self.fetch_id

app/upload/models.py
from django.db import models

# Create your models here.

app/fetcher/views.py
import os
from django.shortcuts import render, redirect
from .tasks import generate_and_check_fetch_id, get_id_path, create_directory, rsync_process, download_fetch, get_file_name
from .settings import CURRENT_RELEASE, SPECIES_LIST, ENSEMBL_RELEASE_LIST
from .models import Fetch


def reference_fetcher_view(request, *args, **kwargs):
    # get template_name
    template_name = 'fetcher/fetcher.html'

    if request.method == "POST":
        # save user input as variables
        species_name = request.POST.get("species_name")
        ensembl_version = str(request.POST.get("ensembl_version"))
        print("ensembl_version:", ensembl_version)
        reference_type = request.POST.get("selector")

        if species_name.lower() not in SPECIES_LIST:
            # pass
            return redirect('fetcher:missing')

        # if the chosen Ensembl version is not a valid version or no version is provided default to current release
        if ensembl_version not in ENSEMBL_RELEASE_LIST:
            ensembl_version = CURRENT_RELEASE

        if Fetch.objects.filter(species=species_name.strip().lower().replace(" ", "_"),
                                ensembl_version=ensembl_version,reference=reference_type):
            fetch = Fetch.objects.get(
                species=species_name.strip().lower().replace(" ", "_"), 
                ensembl_version=ensembl_version, 
                reference=reference_type
                )

            existing_id = fetch.fetch_id

            print(f'Found existing copy of requested file at fetch_id {existing_id}')
            
            existing_fetch = get_file_name(existing_id)

            return download_fetch(fetch_id=existing_id, file=existing_fetch)

        # generate fetch_id variable
        fetch_id = generate_and_check_fetch_id()

        # get id_path in mediafiles directory
        id_path = get_id_path(fetch_id)

        # create fetch directory
        create_directory(id_path)

        # change to fetch directory
        os.chdir(id_path)

        destination = "."

        file = rsync_process(species_name=species_name, ensembl_version=ensembl_version, reference_type=reference_type,
                             destination=destination)

        print("file: ", file)
        fetch = Fetch(
            fetch_id=fetch_id, 
            species=species_name.strip().lower().replace(" ", "_"), 
            ensembl_version=ensembl_version, 
            reference=reference_type
        )
        fetch.save()

        return download_fetch(fetch_id=fetch_id, file=file)
        
    return render(request, template_name)


def missing_species_view(request, *args, **kwargs):
    # get template_name
    template_name = 'fetcher/missing_species.html'

    return render(request, template_name)


def ensembl_list_view(request, *args, **kwargs):
    # get template_name
    template_name = 'fetcher/species_list.html'

    spec_list = []
    for species in SPECIES_LIST:
        spec_list.append(species.capitalize())

    return render(request, template_name, context={"species_list": spec_list})


def version_list_view(request, *args, **kwargs):
    # get template_name
    template_name = 'fetcher/version_list.html'

    return render(request, template_name, context={"version_list": ENSEMBL_RELEASE_LIST})

app/upload/views.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage


def image_upload(request):
    if request.method == "POST" and request.FILES["image_file"]:
        image_file = request.FILES["image_file"]
        fs = FileSystemStorage()
        filename = fs.save(image_file.name, image_file)
        image_url = fs.url(filename)
        print(image_url)
        return render(request, "upload.html", {
            "image_url": image_url
        })
    return render(request, "upload.html")

app/fetcher/templates/fetcher/fetcher.html
{% extends 'base.html' %}

{% block title %}Reference Fetcher{% endblock %}
{% load static %}
<!-- {% block extrahead %}<link rel="stylesheet" href="{% static "run/style.css" %}">{% endblock %} -->

{% block content %}

    <p><h4>Reference Fetcher</h4></p>

    <p>
        The Reference Fetcher provides fast access different bioinformatic references from the Ensembl database.
    </p>
    <p>
        After entering the taxonomic name of the organism you require references for and selecting the type of
        reference you need the Fetcher will search Ensembl for that reference and provide it to you in form of a download.
    </p>
    <p>
        A list of all available species can be found <a href="{% url 'fetcher:species_list' %}" target="_blank">here</a>.
    </p>
    <p>
        A list of all available Ensembl versions can be found <a href="{% url 'fetcher:version_list' %}" target="_blank">here</a>.
    </p>

    <form action="." method="post" enctype="multipart/form-data" onsubmit="pop_up('Finding the requested reference may take a moment.\nPlease have patience.')">
        {% csrf_token %}
{#        <p>#}
{#            <label for="id_species">Enter species name: </label>#}
{#            <input id="id_species" class="ml-4 no-w-bg" type="text" name="species_name">#}
{#            <small><em>#}
{##}
{#            </em></small>#}
{#        </p>#}
{##}
{#        <p>#}
{#            <label for="id_ensembl_version">Enter the Ensembl version you would like to use: </label>#}
{#            <input id="id_ensembl_version" class="text-like ml-4" type="number" name="ensembl_version">#}
{#            <br>#}
{#            <small><em>#}
{#                Leave this field empty to download the latest version of the reference.#}
{#            </em></small>#}
{#        </p>#}
{##}
{#        <p>#}
{#            <label for="id_selector">Please select the type of reference you would like to fetch:</label>#}
{#            <select id="id_selector" name="selector">#}
{#                <option value="gtf">GTF file</option>#}
{#                <option value="gff3">GFF3 file</option>#}
{#                <option value="fasta">FASTA file</option>#}
{#                <option value="fasta_fai">FASTA index files</option>#}
{#            </select>#}
{#            <small><em>#}
{##}
{#            </em></small>#}
{#        </p>#}

        <table>
            <tbody>
                <tr>
                    <td class="noBorder"><label class="float-right" for="id_species">Enter species name: </label></td>
                    <td class="noBorder"><input id="id_species" class="no-w-bg" type="text" name="species_name"></td>
                </tr>
                <tr>
                    <td class="noBorder"><label class="float-right" for="id_ensembl_version">Enter the Ensembl version you would like to use: </label></td>
                    <td class="noBorder"><input id="id_ensembl_version" class="text-like" type="number" name="ensembl_version"></td>
                </tr>
                <tr><td class="noBorder" colspan="2">
                    <small><em class="float-right">
                        Leave this field empty to download the latest version of the reference.
                    </em></small>
                </td></tr>
                <tr>
                    <td class="noBorder"><label class="float-right" for="id_selector">Please select the type of reference you would like to fetch:</label></td>
                    <td class="noBorder">
                        <select id="id_selector" name="selector">
                            <option value="gtf">GTF file</option>
                            <option value="gff3">GFF3 file</option>
                            <option value="fasta">FASTA file</option>
                            <option value="fasta_fai">FASTA index files</option>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>

{#        <div id="id_chromosome_selector" style="display: none">#}
{#            <select>#}
{#            #}
{#            </select>#}
{#        </div>#}
        <br>
        <button type="submit" name="fetch_reference">Fetch!</button>
    </form>

    <script>
        function pop_up(display_text) {
            alert(display_text);
        }

        {#document.onload {#}
        {#    const selector = document.getElementById("id_selector")#}
        {#    const chromosome_selector = document.getElementById("id_chromosome_selector")#}
        {##}
        {#    if (selector.value === "fasta"#}
        {##}
        {#    chromosome_selector.style.display = "none";}#}

        document.addEventListener("DOMContentLoaded", () => {
            const selector = document.getElementById("id_selector");

            selector.addEventListener("change", () => {
                const chromosome_selector = document.getElementById("id_chromosome_selector");
                if (selector.value === "fasta") {
                    chromosome_selector.style.display = "block";
                } else {
                    chromosome_selector.style.display = "none";
                }
            })
        })
    </script>

{% endblock %}

app/fetcher/templates/fetcher/missing_species.html
{% extends 'base.html' %}

{% block title %}Species not found{% endblock %}
{% load static %}

{% block content %}

    <p><h4>Entered a non valid species</h4></p>

    <p>
        You are looking for a refernce for a species not available in our Ensembl list.
    </p>
    <p>
        The button below will take you back to the previous page.
    </p>
    <p>
        <a href="http://0.0.0.0:8000/list/" target="_blank">Here</a> a list of all species available can be found.
    </p>


    <p style="padding: 0 7em 2em 0;">
        <input class="back-button" type="button" onclick="history.back();" value="Take me back">
    </p>


{% endblock %}

app/fetcher/templates/fetcher/species_list.html
{% extends 'base.html' %}

{% block title %}Ensembl species List{% endblock %}
{% load static %}
<!-- {% block extrahead %}<link rel="stylesheet" href="{% static "run/style.css" %}">{% endblock %} -->

{% block content %}

    <p><h4>Available Ensembl species list</h4></p>

    {% if species_list %}
        <div class="center">
        <table id="species_table">
            <thead>
                <tr>
                    <th><input type="text" class="search-input" placeholder="Species"></th>
                </tr>
            </thead>
            <tbody>
                {% for species in species_list %}
                <tr>
                    <td>{{ species }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    {% else %}
        <p>You should not be seeing this. If you are seeing this, something is going wrong.</p>
    {% endif %}


    <p style="padding: 0 7em 2em 0;">
        <input class="back-button" type="button" onclick="history.back();" value="Take me back">
    </p>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            document.querySelectorAll(".search-input").forEach(inputField => {
                const tableRows = inputField.closest("table").querySelectorAll("tbody tr");
                const headerCell = inputField.closest("th");
                const otherHeaderCells = inputField.closest("tr").querySelectorAll("th");
                const columnIndex = Array.from(otherHeaderCells).indexOf(headerCell);
                const searchableCells = Array.from(tableRows)
                    .map(row => row.querySelectorAll("td")[columnIndex])

                inputField.addEventListener("input", () => {
                    const searchQuery = inputField.value.toLowerCase();

                    for (const tableCell of searchableCells) {
                        const row = tableCell.closest("tr");
                        const value = tableCell.textContent
                            .toLowerCase()
                            .replace(",", "");

                        row.style.visibility = null;

                        if (value.search(searchQuery) === -1) {
                            row.style.visibility = "collapse";
                        }
                    }
                })
            })
        })
    </script>


{% endblock %}

app/fetcher/templates/fetcher/version_list.html
{% extends 'base.html' %}

{% block title %}Ensembl version List{% endblock %}
{% load static %}
<!-- {% block extrahead %}<link rel="stylesheet" href="{% static "run/style.css" %}">{% endblock %} -->

{% block content %}

    <p><h4>Available Ensembl version list</h4></p>


    {% if version_list %}
        <div class="center">
        <table id="version_table">
            <thead>
                <tr>
                    <th><input type="text" class="search-input" placeholder="Version"></th>
                </tr>
            </thead>
            <tbody>
                {% for version in version_list %}
                <tr>
                    <td>{{ version }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    {% else %}
        <p>You should not be seeing this. If you are seeing this, something is going wrong.</p>
    {% endif %}


    <p style="padding: 0 7em 2em 0;">
        <input class="back-button" type="button" onclick="history.back();" value="Take me back">
    </p>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            document.querySelectorAll(".search-input").forEach(inputField => {
                const tableRows = inputField.closest("table").querySelectorAll("tbody tr");
                const headerCell = inputField.closest("th");
                const otherHeaderCells = inputField.closest("tr").querySelectorAll("th");
                const columnIndex = Array.from(otherHeaderCells).indexOf(headerCell);
                const searchableCells = Array.from(tableRows)
                    .map(row => row.querySelectorAll("td")[columnIndex])

                inputField.addEventListener("input", () => {
                    const searchQuery = inputField.value.toLowerCase();

                    for (const tableCell of searchableCells) {
                        const row = tableCell.closest("tr");
                        const value = tableCell.textContent
                            .toLowerCase()
                            .replace(",", "");

                        row.style.visibility = null;

                        if (value.search(searchQuery) === -1) {
                            row.style.visibility = "collapse";
                        }
                    }
                })
            })
        })
    </script>


{% endblock %}

app/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block extrahead %}{% endblock %}
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
            {% block sidebar %}
                <!-- insert default navigation text for every page -->
                <ul class="sidebar-nav">
                    {% if user.is_authenticated %}
                        <li>User: {{ user.get_username }}</li>
                        <!-- <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li> -->
                        <!-- <li><a href="{% url 'logout' %}">Logout</a></li> -->
                        <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                    {% else %}
                        <!-- <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li> -->
                        <!-- <li><a href="{% url 'login' %}">Login</a></li> -->
                        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                    {% endif %}
                </ul>
            {% endblock %}
            </div>
            <div class="col-sm-10">
            {% block content %}
                replace me
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

app/upload/templates/upload.html
{% block content %}

  <form action="{% url "upload" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="image_file">
    <input type="submit" value="submit" />
  </form>

  {% if image_url %}
    <p>File uploaded at: <a href="{{ image_url }}">{{ image_url }}</a></p>
  {% endif %}

{% endblock %}